version: '3.6'
services:
  app:
    build:
      context: .
      target: test
    depends_on:
      - db

    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    command: ['yarn', 'test:e2e', '--runInBand']
    environment:
      - DATABASE_URL=mongodb://db:27017/test
      - NODE_ENV=testing
      - SECRET=secret
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017

