version: "3.6"
services:
    app:
        build:
            context: .
            target: development
        depends_on:
            - db
        volumes:
            - ./src:/app/src
        ports:
            - 3000:3000
        environment:
            - DATABASE_URL=mongodb://db:27017/dev
            - NODE_ENV=development
            - SECRET=secret
    db:
      image: mongo
      restart: always
      ports:
          - 27017
